[project]
name = "sd-turbo-genai"
version = "0.1.0"
description = "Generación de una imagen a partir de una descripción"
readme = "README.md"
authors = [{ name = "Edward Avila" }]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.15.0",
    "diffusers>=0.41.0",
    "torch>=2.14.1",
    "transformers>=5.19.0",
]

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
